using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;

namespace leveledlistresolver
{
    public class Program
    {
        private static Lazy<ProgramSettings> _lazySettings = null!;
        public static ProgramSettings Settings => _lazySettings.Value;

        public static Task<int> Main(string[] args)
        {
            return SynthesisPipeline
                .Instance.AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _lazySettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "LeveledListResolver.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Apply(state);
        }

        public static void Apply(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.WriteLine(
                "Report issues at https://github.com/OddDrifter/leveledlistresolver/issues"
            );
            Console.WriteLine();

            var loadOrder = state.LoadOrder;

            var blacklistedPlugins = Settings.GetBlacklistedPlugins();

            loadOrder
                .Items.Select(static i => i.Mod)
                .NotNull()
                .Where(static i =>
                    string.Equals(
                        i.ModHeader.Author,
                        "Bashed Patch",
                        StringComparison.OrdinalIgnoreCase
                    )
                )
                .Where(static i =>
                    i.LeveledItems.Any() || i.LeveledNpcs.Any() || i.LeveledSpells.Any()
                )
                .ForEach(i => blacklistedPlugins.Add(i.ModKey));

            bool removed = blacklistedPlugins.Any();
            while (removed)
            {
                removed = false;
                foreach (var listing in loadOrder.Items)
                {
                    if (listing is not { Enabled: true, Mod: { } })
                        continue;

                    if (
                        listing.Mod.MasterReferences.Any(i => blacklistedPlugins.Contains(i.Master))
                    )
                    {
                        if (blacklistedPlugins.Add(listing.ModKey))
                            removed = true;
                    }
                }
            }

            if (blacklistedPlugins.Any())
            {
                Console.WriteLine("Blacklisted plugins:");
                foreach (var (plugin, last) in blacklistedPlugins.IterateMarkLast())
                {
                    if (loadOrder.RemoveKey(plugin))
                        Console.WriteLine(
                            $"  - {plugin}{(last ? Environment.NewLine : string.Empty)}"
                        );
                }
            }

            var enabledAndExisting = loadOrder
                .PriorityOrder.OnlyEnabledAndExisting()
                .ToImmutableArray();
            var comparer = ModKey.LoadOrderComparer(loadOrder.Keys.ToImmutableArray());

            int patchedItems = 0,
                skippedItems = 0;
            int patchedNpcs = 0,
                skippedNpcs = 0;
            int patchedSpells = 0,
                skippedSpells = 0;
            int patchedContainers = 0,
                skippedContainers = 0;

            Console.WriteLine("Processing Leveled Items...");
            Console.WriteLine(new string('=', 50));
            foreach (
                var leveledItem in enabledAndExisting
                    .LeveledItem()
                    .WinningOverrides()
                    .OrderBy(static i => i.FormKey.ModKey, comparer)
                    .ThenBy(static i => i.FormKey.ID)
            )
            {
                if (RecordPatcher.TryPatch(state, leveledItem, out LeveledItem? _))
                {
                    patchedItems++;
                }
                else
                {
                    skippedItems++;
                }
            }
            Console.WriteLine($"Leveled Items: {patchedItems} patched, {skippedItems} skipped");
            Console.WriteLine();

            Console.WriteLine("Processing Leveled NPCs...");
            Console.WriteLine(new string('=', 50));
            foreach (
                var leveledNpc in enabledAndExisting
                    .LeveledNpc()
                    .WinningOverrides()
                    .OrderBy(static i => i.FormKey.ModKey, comparer)
                    .ThenBy(static i => i.FormKey.ID)
            )
            {
                if (RecordPatcher.TryPatch(state, leveledNpc, out LeveledNpc? _))
                {
                    patchedNpcs++;
                }
                else
                {
                    skippedNpcs++;
                }
            }
            Console.WriteLine($"Leveled NPCs: {patchedNpcs} patched, {skippedNpcs} skipped");
            Console.WriteLine();

            Console.WriteLine("Processing Leveled Spells...");
            Console.WriteLine(new string('=', 50));
            foreach (
                var leveledSpell in enabledAndExisting
                    .LeveledSpell()
                    .WinningOverrides()
                    .OrderBy(static i => i.FormKey.ModKey, comparer)
                    .ThenBy(static i => i.FormKey.ID)
            )
            {
                if (RecordPatcher.TryPatch(state, leveledSpell, out LeveledSpell? _))
                {
                    patchedSpells++;
                }
                else
                {
                    skippedSpells++;
                }
            }
            Console.WriteLine($"Leveled Spells: {patchedSpells} patched, {skippedSpells} skipped");
            Console.WriteLine();

            Console.WriteLine("Processing Containers...");
            Console.WriteLine(new string('=', 50));
            foreach (
                var container in enabledAndExisting
                    .Container()
                    .WinningOverrides()
                    .OrderBy(static i => i.FormKey.ModKey, comparer)
                    .ThenBy(static i => i.FormKey.ID)
            )
            {
                if (RecordPatcher.TryPatch(state, container, out Container? copy))
                {
                    state.PatchMod.Containers.Set(copy);
                    patchedContainers++;
                }
                else
                {
                    skippedContainers++;
                }
            }
            Console.WriteLine(
                $"Containers: {patchedContainers} patched, {skippedContainers} skipped"
            );
            Console.WriteLine();

            Console.WriteLine(new string('=', 70));
            Console.WriteLine("SUMMARY");
            Console.WriteLine(new string('=', 70));
            int totalPatched = patchedItems + patchedNpcs + patchedSpells + patchedContainers;
            int totalSkipped = skippedItems + skippedNpcs + skippedSpells + skippedContainers;
            Console.WriteLine($"Total Patched: {totalPatched}");
            Console.WriteLine($"Total Skipped: {totalSkipped}");
            Console.WriteLine();
            Console.WriteLine($"  Leveled Items: {patchedItems} patched, {skippedItems} skipped");
            Console.WriteLine($"  Leveled NPCs: {patchedNpcs} patched, {skippedNpcs} skipped");
            Console.WriteLine(
                $"  Leveled Spells: {patchedSpells} patched, {skippedSpells} skipped"
            );
            Console.WriteLine(
                $"  Containers: {patchedContainers} patched, {skippedContainers} skipped"
            );
            Console.WriteLine(new string('=', 70));
        }
    }
}
